image: python:3.7.9
clone:
  depth: full
pipelines:
  default:
    - step:
        name: Building Model
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip3 install --upgrade pip setuptools wheel
          - pip3 install -r requirements.txt
          - python model.py
    - step: 
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
          - pip3 install --upgrade pip setuptools wheel
          - pip3 install -r requirements.txt
          - python app.py